# netlify.toml - Jednostavna konfiguracija

[build]
  # Bez build commanda - samo publiciraj datoteke
  publish = "."

# Redirects
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
